Adiciona um título à lista
brunomiguel/antinonio pull request #22
Opened 2020-02-03 18:48 UTC by rfgamaral

Adiciona um simples título à lista para melhor identificação nas aplicações.

Ou seja, usando como exemplo o uBlock Origin, ter isto:

![image](https://user-images.githubusercontent.com/96476/73681229-d2548200-46b5-11ea-8b8e-0cbbc34ddd90.png)

Em vez de isto:

![image](https://user-images.githubusercontent.com/96476/73681181-b9e46780-46b5-11ea-8148-2b645b529499.png)

2020-02-03 20:19 UTC, PJFonseca commented
Alguma ideia como podemos fazer isso?

2020-02-03 20:30 UTC, brunomiguel requested changes
Sendo uma lista direcionada para utilizadores portugueses, o título deveria ser (idealmente) em pt-PT

2020-02-04 09:34 UTC, rfgamaral commented
> 
> 
> Sendo uma lista direcionada para utilizadores portugueses, o título deveria ser (idealmente) em pt-PT

Queres que mude para `Anti Nónio Lista` ou tens outra sugestão?

2020-02-04 12:16 UTC, brunomiguel commented
> > Sendo uma lista direcionada para utilizadores portugueses, o título deveria ser (idealmente) em pt-PT
> 
> Queres que mude para `Anti Nónio Lista`, `Lista Anti Nónio` ou tens outra sugestão?

Deixo ao teu critério :)

2020-02-04 12:27 UTC, rfgamaral commented
> 
> 
> > > Sendo uma lista direcionada para utilizadores portugueses, o título deveria ser (idealmente) em pt-PT
> > 
> > 
> > Queres que mude para `Anti Nónio Lista`, `Lista Anti Nónio` ou tens outra sugestão?
> 
> Deixo ao teu critério :)

É melhor escolheres tu porque o meu critério é deixar em Inglês 😂

2020-02-06 20:31 UTC, merged